"""Registers the generated set art, icon library and cast (Open Peeps atoms) in the license registry.

Every layer/asset the renderer can touch must have a registry entry (source, license, sha256);
engine/shorts/reports.py refuses to call a render 'clean' otherwise. Idempotent: entries are keyed
by id and refreshed with the file's current sha256.
"""
import datetime
import glob
import hashlib
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = os.path.join(ROOT, "assets/licenses/registry.json")
NOW = datetime.datetime.now(datetime.timezone.utc).isoformat()


def sha(paths):
    h = hashlib.sha256()
    for p in sorted(paths):
        h.update(open(p, "rb").read())
    return h.hexdigest()


def entry(_id, kind, paths, source, lic, author, style, layers):
    return {"source": source, "download_url": "n/a (original work, generated by code in this repo)" if "hand" in source else "see source_url",
            "license": lic, "commercial_use": True, "attribution_required": False, "share_alike": False, "modification_allowed": True,
            "author": author, "downloaded_at": NOW, "style": style, "id": _id, "source_url": "repo://" + os.path.relpath(os.path.dirname(paths[0]), ROOT),
            "sha256": sha(paths), "asset_type": kind, "layers": layers, "riggable": kind == "character", "status": "REGISTERED",
            "status_reason": "ok", "registered_at": NOW}


def main():
    reg = json.load(open(REG))
    items = {a["id"]: a for a in reg["assets"]}
    for set_id in ("night_bedroom", "office_day", "street_dusk"):
        files = glob.glob(os.path.join(ROOT, "assets/environment/generated", set_id, "*.svg"))
        items[f"set_{set_id}"] = entry(f"set_{set_id}", "environment", files, "hand-authored (this project)",
                                       "CC0 (original work, dedicated to public domain)", "infographics-animations project",
                                       "ink-outline flat, matches Open Peeps linework", sorted(os.path.basename(f)[:-4] for f in files))
    cast = glob.glob(os.path.join(ROOT, "assets/character/cast/*.svg"))
    items["cast_open_peeps_v1"] = entry("cast_open_peeps_v1", "character", cast, "Open Peeps by Pablo Stanley (composited by asset_pipeline/cast_builder.py)",
                                        "CC0 1.0", "Pablo Stanley", "hand-drawn monochrome", ["body x11", "head x3 characters x19 faces"])
    items["cast_open_peeps_v1"]["source_url"] = "https://www.openpeeps.com/"
    icon_files = [os.path.join(ROOT, "asset_pipeline/icons.py")]
    items["icons_ink_v1"] = entry("icons_ink_v1", "prop", icon_files, "hand-authored (this project)",
                                  "CC0 (original work, dedicated to public domain)", "infographics-animations project", "ink icons", ["14 icons"])
    items["rig_art_layered_v1"] = entry("rig_art_layered_v1", "character", [os.path.join(ROOT, "asset_pipeline/rig_art.py")], "hand-authored (this project)",
                                        "CC0 (original work, dedicated to public domain)", "infographics-animations project",
                                        "ink torso/sleeves/hands/phone/face features drawn in Open Peeps linework", ["torso", "arms", "hands", "phone", "eyes", "brows", "mouth"])
    reg["assets"] = list(items.values())
    json.dump(reg, open(REG, "w"), indent=2, ensure_ascii=False)
    return len(reg["assets"])


if __name__ == "__main__":
    print("registry entries:", main())
